services:
  postgres:
    image: postgres:16
    container_name: mini-shopify-postgres
    environment:
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify
      POSTGRES_DB: shopify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/init.sql:/docker-entrypoint-initdb.d/init.sql

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - postgres

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "4000:4000"
    env_file:
      - ./services/inventory-service/.env
    depends_on:
      - postgres

volumes:
  postgres_data: